name: Docs Quality

on:
  pull_request:
    branches: ["**"]
    paths:
      - "**/*.md"
      - ".markdownlint.jsonc"
      - ".lychee.toml"
      - ".github/workflows/docs-quality.yml"
  workflow_dispatch: {}

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
          config: .markdownlint.jsonc
          ignore: |
            **/node_modules/**
            **/.git/**

  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Link Check
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config .lychee.toml
            --no-progress
            --max-concurrency 8
            --retry-wait-time 2
            --verbose
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
